[package]
name = "PizBoat"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
rust-pigpio = "0.2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tungstenite = "0.21"
